version: "2"
services:
  browser-automation-api:
    container_name: browser-automation-api
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./chrome-profiles:/chrome-profiles
    networks:
      - x11

networks:
  x11:
